---
platform: linux

params:
  GIT_SSH_KEY:
  GOPRIVATE: gitlab.eng.vmware.com
  MAKE_TARGET: test
  REGISTRY_SERVER:
  REGISTRY_USERNAME:
  REGISTRY_PASSWORD:

inputs:
  - name: source

run:
  path: /bin/bash
  dir: source
  args:
    - -exc
    - |
      if [ "${MAKE_TARGET}" == "test-enemies" ] ; then
        export DOCKER_API_VERSION=1.39
        source /docker-lib.sh
        start_docker

        set +x
        echo "${REGISTRY_PASSWORD}" | docker login "${REGISTRY_SERVER}" --username "${REGISTRY_USERNAME}" --password-stdin
        set -x
      fi

      ci/scripts/install-git-ssh-key
      make "${MAKE_TARGET}"
