---
platform: linux

params:
  GIT_SSH_KEY:
  GOPRIVATE: gitlab.eng.vmware.com
  MAKE_TARGET: test

inputs:
  - name: source

run:
  path: /bin/bash
  dir: source
  args:
    - -exc
    - |
      if [ "${MAKE_TARGET}" == "test-enemies" ] ; then
        export DOCKER_API_VERSION=1.39
        source /docker-lib.sh
        start_docker
      fi

      ci/scripts/install-git-ssh-key
      make "${MAKE_TARGET}"
