---
platform: linux

params:
  GIT_SSH_KEY:
  GOPRIVATE: gitlab.eng.vmware.com
  REGISTRY_AUTH: harbor-repo.vmware.com=((private-harbor.username)):((private-harbor.token))

inputs:
  - name: source

run:
  path: /bin/bash
  dir: source
  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker

      ci/scripts/install-git-ssh-key
      make test
