---
platform: linux

params:
  GIT_SSH_KEY:
  GOPRIVATE: gitlab.eng.vmware.com
  MAKE_TARGET: test

inputs:
  - name: source

run:
  path: /bin/bash
  dir: source
  args:
    - -exc
    - |
      ci/scripts/install-git-ssh-key
      make "${MAKE_TARGET}"
