---
resource_types:
  - name: gl-release
    type: registry-image
    source:
      repository: harbor-repo.vmware.com/dockerhub-proxy-cache/orangeopensource/gitlab-release-resource
      tag: v1.0.4
      username: ((harbor.username))
      password: ((harbor.token))

  - name: chartmuseum
    type: docker-image
    source:
      repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cathive/concourse-chartmuseum-resource
      tag: v1.0.0

resources:
  - name: source
    type: git
    icon: gitlab
    source:
      uri: git@gitlab.eng.vmware.com:marketplace-partner-eng/relok8s.git
      private_key: ((gitlab.private_key))
      branch: main
      ignore_paths:
        - ci/Dockerfile
        - ci/pipeline.yaml

  - name: golang-image
    type: registry-image
    source:
      repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/golang
      tag: 1.16
      username: ((harbor.username))
      password: ((harbor.token))

  - name: test-image-source
    type: git
    icon: gitlab
    source:
      uri: git@gitlab.eng.vmware.com:marketplace-partner-eng/relok8s.git
      private_key: ((gitlab.private_key))
      branch: main
      paths:
        - ci/Dockerfile

  - name: test-image
    type: docker-image
    icon: docker
    source:
      repository: harbor-repo.vmware.com/tanzu_isv_engineering/relok8s-test-image
      username: ((harbor.username))
      password: ((harbor.token))

  - name: docker-image
    type: docker-image
    icon: docker
    source:
      repository: harbor-repo.vmware.com/tanzu_isv_engineering/relok8s
      username: ((harbor.username))
      password: ((harbor.token))

  - name: release
    type: gl-release
    icon: gitlab
    source:
      repository: marketplace-partner-eng/relok8s
      access_token: ((gitlab.access_token))
      gitlab_api_url: https://gitlab.eng.vmware.com

  - name: version
    type: semver
    icon: gitlab
    source:
      driver: git
      uri: git@gitlab.eng.vmware.com:marketplace-partner-eng/relok8s.git
      private_key: ((gitlab.private_key))
      branch: main
      file: version
      commit_message: "[ci skip] bump version to %version%"

  - name: source-chart
    type: chartmuseum
    icon: kubernetes
    source:
      server_url: https://harbor-repo.vmware.com/api/chartrepo/tanzu_isv_engineering/charts
      chart_name: test-chart-product
      basic_auth_username: ((harbor.username))
      basic_auth_password: ((harbor.token))
      harbor_api: true

  - name: rewritten-chart
    type: chartmuseum
    icon: kubernetes
    source:
      server_url: https://harbor-repo.vmware.com/api/chartrepo/tanzu_isv_engineering_private/charts
      chart_name: test-chart-product
      basic_auth_username: ((harbor-private.username))
      basic_auth_password: ((harbor-private.token))
      harbor_api: true

jobs:
  - name: build-test-image
    plan:
      - get: test-image-source
        trigger: true
      - put: test-image
        params:
          build: .
          dockerfile: test-image-source/ci/Dockerfile
          tag_as_latest: true

  - name: test
    plan:
      - in_parallel:
          - get: golang-image
          - get: test-image
            passed:
              - build-test-image
          - get: source
            trigger: true
      - task: run-unit-tests
        image: golang-image
        file: source/ci/tasks/test.yaml
        params:
          GIT_SSH_KEY: ((gitlab.private_key))
          MAKE_TARGET: test-units
      - task: run-feature-tests
        image: test-image
        file: source/ci/tasks/test.yaml
        params:
          GIT_SSH_KEY: ((gitlab.private_key))
          MAKE_TARGET: test-features
      - task: run-external-tests
        image: test-image
        privileged: true
        file: source/ci/tasks/test.yaml
        params:
          GIT_SSH_KEY: ((gitlab.private_key))
          MAKE_TARGET: test-external
          REGISTRY_SERVER: harbor-repo.vmware.com
          REGISTRY_USERNAME: ((harbor-private.username))
          REGISTRY_PASSWORD: ((harbor-private.token))

  - name: build
    serial_groups: [version]
    plan:
      - in_parallel:
        - get: golang-image
          passed:
            - test
        - get: source
          trigger: true
          passed:
            - test
        - get: version
          params:
            bump: patch
      - task: build
        image: golang-image
        file: source/ci/tasks/build.yaml
        params:
          GIT_SSH_KEY: ((gitlab.private_key))
      - put: docker-image
        inputs:
          - build
          - source
          - version
        params:
          build: .
          dockerfile: source/Dockerfile
          tag_file: version/version
          tag_as_latest: true
      - put: release
        inputs: [build, source, version]
        params:
          commitish: source/.git/ref
          tag: version/version
          globs:
            - build/*
      - put: version
        params:
          file: version/version
        inputs: detect

  - name: bump-minor-version
    serial_groups: [version]
    plan:
      - put: version
        inputs: detect
        params:
          bump: minor

  - name: relocate-chart
    plan:
      - in_parallel:
        - get: docker-image
          passed:
            - build
          trigger: true
        - get: source-chart
      - task: relocate
        image: docker-image
        privileged: true
        config:
          platform: linux
          params:
            DESTINATION_REGISTRY: https://harbor-repo.vmware.com/tanzu_isv_engineering_private
            DESTINATION_REGISTRY_USERNAME: ((harbor-private.username))
            DESTINATION_REGISTRY_PASSWORD: ((harbor-private.token))
          inputs:
            - name: source-chart
          outputs:
            - name: rewritten-chart
          run:
            path: bash
            args:
              - -exc
              - |
                source /docker-lib.sh
                start_docker

                echo "${DESTINATION_REGISTRY_PASSWORD}" | docker login ${DESTINATION_REGISTRY} --username ${DESTINATION_REGISTRY_USERNAME} --password-stdin

                cat > image-patterns.yaml <<EOF
                ---
                - "{{ .image.repository }}:{{ .image.tag }}"
                EOF
                relok8s chart move source-chart/*.tgz \
                  --yes \
                  --image-patterns image-patterns.yaml \
                  --registry harbor-repo.vmware.com \
                  --repo-prefix tanzu_isv_engineering_private
                mv *.relocated.tgz rewritten-chart/chart.tgz
      - put: rewritten-chart
        params:
          chart: rewritten-chart/chart.tgz
