---
resource_types:
  - name: chartmuseum
    type: docker-image
    source:
      repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cathive/concourse-chartmuseum-resource
      tag: v1.0.0

resources:
  - name: source
    type: git
    icon: github
    source:
      uri: git@github.com:vmware-tanzu/asset-relocation-tool-for-kubernetes.git
      private_key: ((github.private_key))
      branch: main
      ignore_paths:
        - ci/Dockerfile
        - ci/pipeline.yaml

  - name: test-image-source
    type: git
    icon: github
    source:
      uri: git@github.com:vmware-tanzu/asset-relocation-tool-for-kubernetes.git
      private_key: ((github.private_key))
      branch: main
      paths:
        - ci/Dockerfile

  - name: test-image
    type: docker-image
    icon: docker
    source:
      repository: harbor-repo.vmware.com/tanzu_isv_engineering/relok8s-test-image
      username: ((harbor.username))
      password: ((harbor.token))

  - name: docker-image
    type: registry-image
    icon: docker
    source:
      repository: projects.registry.vmware.com/tanzu_isv_engineering/relok8s
      username: ((harbor-public.username))
      password: ((harbor-public.token))

  - name: release
    type: github-release
    icon: github
    source:
      owner: vmware-tanzu
      repository: asset-relocation-tool-for-kubernetes
      access_token: ((github.access_token))

  - name: version
    type: semver
    icon: github
    source:
      driver: git
      uri: git@github.com:vmware-tanzu/asset-relocation-tool-for-kubernetes.git
      private_key: ((github.private_key))
      branch: main
      file: version
      commit_message: "[ci skip] bump version to %version%"

  - name: source-chart
    type: chartmuseum
    icon: kubernetes
    source:
      server_url: https://harbor-repo.vmware.com/api/chartrepo/tanzu_isv_engineering/charts
      chart_name: test-chart-product
      basic_auth_username: ((harbor.username))
      basic_auth_password: ((harbor.token))
      harbor_api: true

jobs:
  - name: build-test-image
    plan:
      - get: test-image-source
        trigger: true
      - put: test-image
        params:
          build: test-image-source
          dockerfile: test-image-source/ci/Dockerfile
          tag_as_latest: true

  - name: test
    plan:
      - in_parallel:
          - get: test-image
            passed:
              - build-test-image
            trigger: true
          - get: source
            trigger: true
      - task: run-unit-tests
        image: test-image
        file: source/ci/tasks/test.yaml
        params:
          MAKE_TARGET: test-units
      - task: run-feature-tests
        image: test-image
        file: source/ci/tasks/test.yaml
        params:
          MAKE_TARGET: test-features
      - task: run-external-tests
        image: test-image
        file: source/ci/tasks/test.yaml
        params:
          MAKE_TARGET: test-external
          REGISTRY_SERVER: harbor-repo.vmware.com
          REGISTRY_USERNAME: ((harbor-private.username))
          REGISTRY_PASSWORD: ((harbor-private.token))

  - name: build
    serial_groups: [version]
    plan:
      - in_parallel:
        - get: test-image
          passed:
            - test
        - get: source
          trigger: true
          passed:
            - test
        - get: version
          params:
            bump: patch
      - task: build
        image: test-image
        file: source/ci/tasks/build.yaml
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: harbor-repo.vmware.com/dockerhub-proxy-cache/concourse/oci-build-task
              username: ((harbor.username))
              password: ((harbor.token))
          inputs:
            - name: build
            - name: source
              path: .
          outputs:
            - name: image
          run:
            path: build
      - put: docker-image
        inputs:
          - image
          - version
        params:
          image: image/image.tar
          additional_tags: version/version
      - put: release
        inputs: [build, source, version]
        params:
          name: version/version
          tag: version/version
          commitish: source/.git/ref
          globs:
            - build/*
      - put: version
        params:
          file: version/version
        inputs: detect

  - name: bump-minor-version
    serial_groups: [version]
    plan:
      - put: version
        inputs: detect
        params:
          bump: minor

  - name: relocate-chart
    plan:
      - in_parallel:
        - get: docker-image
          passed:
            - build
          trigger: true
        - get: source-chart
      - task: relocate
        image: docker-image
        config:
          platform: linux
          params:
            REGISTRY_SERVER: harbor-repo.vmware.com
            REGISTRY_USERNAME: ((harbor-private.username))
            REGISTRY_PASSWORD: ((harbor-private.token))
          inputs:
            - name: source-chart
          outputs:
            - name: rewritten-chart
          run:
            path: bash
            args:
              - -exc
              - |
                docker-login.sh "${REGISTRY_SERVER}" "${REGISTRY_USERNAME}" "${REGISTRY_PASSWORD}"

                cat > image-patterns.yaml <<EOF
                ---
                - "{{ .image.repository }}:{{ .image.tag }}"
                EOF

                relok8s chart move source-chart/*.tgz \
                  --yes \
                  --image-patterns image-patterns.yaml \
                  --registry "${REGISTRY_SERVER}" \
                  --repo-prefix tanzu_isv_engineering_private
                mv *.relocated.tgz rewritten-chart/chart.tgz
      - task: print-diff
        image: docker-image
        config:
          platform: linux
          inputs:
            - name: source-chart
            - name: rewritten-chart
          run:
            path: bash
            args:
              - -exc
              - |
                # NOTE: The leading ! is because it is an error condition if there are no differences in the two files
                ! diff --context=3 \
                  <(tar xzfO source-chart/*.tgz test-chart-product/values.yaml) \
                  <(tar xzfO rewritten-chart/chart.tgz test-chart-product/values.yaml)
