---
resource_types:
  - name: gl-release
    type: registry-image
    source:
      repository: harbor-repo.vmware.com/dockerhub-proxy-cache/orangeopensource/gitlab-release-resource
      tag: v1.0.4
      username: ((harbor.username))
      password: ((harbor.token))

resources:
  - name: source
    type: git
    icon: gitlab
    source:
      uri: git@gitlab.eng.vmware.com:marketplace-partner-eng/chart-mover.git
      private_key: ((gitlab.private_key))
      branch: master
      ignore_paths:
        - ci/Dockerfile
        - ci/pipeline.yaml

  - name: golang-image
    type: registry-image
    source:
      repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/golang
      tag: 1.16
      username: ((harbor.username))
      password: ((harbor.token))

  - name: test-image-source
    type: git
    icon: gitlab
    source:
      uri: git@gitlab.eng.vmware.com:marketplace-partner-eng/chart-mover.git
      private_key: ((gitlab.private_key))
      branch: master
      paths:
        - ci/Dockerfile

  - name: test-image
    type: docker-image
    icon: docker
    source:
      repository: harbor-repo.vmware.com/tanzu_isv_engineering/chart-mover-test-image
      username: ((harbor.username))
      password: ((harbor.token))

  - name: docker-image
    type: docker-image
    icon: docker
    source:
      repository: harbor-repo.vmware.com/tanzu_isv_engineering/chart-mover
      username: ((harbor.username))
      password: ((harbor.token))

  - name: release
    type: gl-release
    icon: gitlab
    source:
      repository: marketplace-partner-eng/chart-mover
      access_token: ((gitlab.access_token))
      gitlab_api_url: https://gitlab.eng.vmware.com

  - name: version
    type: semver
    icon: gitlab
    source:
      driver: git
      uri: git@gitlab.eng.vmware.com:marketplace-partner-eng/chart-mover.git
      private_key: ((gitlab.private_key))
      branch: master
      file: version
      commit_message: "[ci skip] bump version to %version%"

jobs:
  - name: build-test-image
    plan:
      - get: test-image-source
        trigger: true
      - put: test-image
        params:
          build: .
          dockerfile: test-image-source/ci/Dockerfile
          tag_as_latest: true

  - name: test
    plan:
      - in_parallel:
          - get: golang-image
          - get: source
            trigger: true
      - task: run-unit-tests
        image: golang-image
        file: source/ci/tasks/test.yaml
        params:
          GIT_SSH_KEY: ((gitlab.private_key))
          MAKE_TARGET: test-units
      - task: run-feature-tests
        image: golang-image
        file: source/ci/tasks/test.yaml
        params:
          GIT_SSH_KEY: ((gitlab.private_key))
          MAKE_TARGET: test-features

  - name: build
    serial_groups: [version]
    plan:
      - in_parallel:
        - get: golang-image
          passed:
            - test
        - get: source
          trigger: true
          passed:
            - test
        - get: version
          params:
            bump: patch
      - task: build
        image: golang-image
        file: source/ci/tasks/build.yaml
        params:
          GIT_SSH_KEY: ((gitlab.private_key))
      - put: docker-image
        inputs:
          - build
          - source
          - version
        params:
          build: .
          dockerfile: source/Dockerfile
          tag_file: version/version
          tag_as_latest: true
      - put: release
        inputs: [build, source, version]
        params:
          commitish: source/.git/ref
          tag: version/version
          globs:
            - build/*
      - put: version
        params:
          file: version/version
        inputs: detect

  - name: bump-minor-version
    serial_groups: [version]
    plan:
      - put: version
        inputs: detect
        params:
          bump: minor